### ISSUE TITLE
Mention detached mode in readme

### ISSUE THREAD

**Issue by oik741** [openenergyprojects/joomla-docker-inproduction#2]
Hi, 
`docker-compose -f docker-compose-joomla.yml up &`
should be replaced by
`docker-compose -f docker-compose-joomla.yml up -d`

use detached mode instead of running process in background mode(in this mode process will be killed if you'll close your terminal).

Thx for compose file!)

**Comment by openenergyprojects** [comment]
Thanks!
Solved since then, forgot to close ;)
